# routers/smart_tasks.py
# Mount in main.py:
#   from routers.smart_tasks import router as smart_tasks_router
#   app.include_router(smart_tasks_router, prefix="/api/tasks", tags=["smart-tasks"])

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from sqlalchemy import cast, Date
from datetime import datetime, timezone, date
from typing import List
from uuid import UUID

from Backend.db.session import get_db
from Backend.routers.auth import get_current_user
from Backend.models.smart_task import SmartDailyTask
from Backend.models.onboarding import UserOnboarding
from Backend.schemas.smart_task import SmartTaskOut, SubmitAnswerRequest, SubmitAnswerResponse
from Backend.services.smart_task_service import generate_smart_daily_tasks
from Backend.services.gemini_service import ask_ai   # reuse your existing ask_ai

router = APIRouter()


def _get_user_profile(user_id, db: Session) -> dict:
    """Mirror of your dashboard get_user_profile — reuse or import directly."""
    ob = db.query(UserOnboarding).filter(UserOnboarding.user_id == user_id).first()
    if not ob:
        return {"user_type": "student", "primary_goal": "grow career", "interests": ["programming"]}
    return {
        "user_type"         : ob.user_type or "student",
        "primary_goal"      : ob.primary_goal or "grow career",
        "twelve_month_goal" : ob.twelve_month_goal or "get a job",
        "interests"         : ob.interests or [],
        "daily_time"        : ob.daily_time or "2-3hours",
        "career_goal"       : ob.career_goal or "",
        "productivity_style": ob.productivity_style or "deep_focus",
        "country"           : ob.country or "India",
        "exam_type"         : ob.exam_type or "",
        "weak_subjects"     : ob.weak_subjects or [],
        "attempt_year"      : ob.attempt_year or "",
        "field_of_study"    : ob.field_of_study or "",
        "education_level"   : ob.education_level or "",
        "primary_skill"     : ob.primary_skill or "",
        "services_offered"  : ob.services_offered or [],
        "monthly_income_goal": ob.monthly_income_goal or "",
        "business_type"     : ob.business_type or "",
        "revenue_stage"     : ob.revenue_stage or "",
        "business_goal"     : ob.business_goal or "",
        "creator_platform"  : ob.creator_platform or "",
        "content_niche"     : ob.content_niche or "",
        "audience_size"     : ob.audience_size or "",
        "creator_growth_goal": ob.creator_growth_goal or "",
    }


# ─────────────────────────────────────────────────────────────────────────────
# GET /api/tasks/today
# Returns today's 3 smart tasks for the current user.
# Auto-generates via Gemini if none exist yet (on-demand fallback).
# ─────────────────────────────────────────────────────────────────────────────

@router.get("/today", response_model=List[SmartTaskOut])
def get_today_smart_tasks(
    db          : Session = Depends(get_db),
    current_user          = Depends(get_current_user),
):
    today = date.today()

    # Check if today's tasks already exist (generated by scheduler or previous call)
    tasks = (
        db.query(SmartDailyTask)
          .filter(
              SmartDailyTask.user_id == current_user.id,
              cast(SmartDailyTask.task_date, Date) == today,
          )
          .order_by(SmartDailyTask.difficulty.desc())   # hard tasks first
          .all()
    )

    if tasks:
        return tasks

    # ── On-demand generation (fallback if scheduler hasn't run yet) ───────────
    profile    = _get_user_profile(current_user.id, db)
    tasks_data = generate_smart_daily_tasks(profile)

    if not tasks_data:
        return []

    saved = []
    for t in tasks_data:
        task = SmartDailyTask(
            user_id           = current_user.id,
            title             = t.get("title", "Today's Task"),
            question          = t.get("question", t.get("description", "")),
            description       = t.get("description", ""),
            difficulty        = t.get("difficulty", "hard"),
            category          = t.get("category", "Learning"),
            skill_tag         = t.get("skill_tag", ""),
            resource_url      = t.get("resource_url", ""),
            priority          = t.get("priority", "high"),
            estimated_minutes = t.get("estimated_minutes", 45),
            xp_reward         = t.get("xp_reward", 50),
            task_date         = datetime.now(timezone.utc),
        )
        db.add(task)
        saved.append(task)

    db.commit()
    for task in saved:
        db.refresh(task)

    return saved


# ─────────────────────────────────────────────────────────────────────────────
# POST /api/tasks/{task_id}/complete
# Marks a task complete (no answer required — just checkbox)
# ─────────────────────────────────────────────────────────────────────────────

@router.post("/{task_id}/complete")
def complete_task(
    task_id     : UUID,
    db          : Session = Depends(get_db),
    current_user          = Depends(get_current_user),
):
    task = db.query(SmartDailyTask).filter(
        SmartDailyTask.id      == task_id,
        SmartDailyTask.user_id == current_user.id,
    ).first()
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")

    task.completed    = True
    task.completed_at = datetime.now(timezone.utc)
    db.commit()
    return {"success": True, "xp_earned": task.xp_reward}


# ─────────────────────────────────────────────────────────────────────────────
# POST /api/tasks/{task_id}/uncomplete
# ─────────────────────────────────────────────────────────────────────────────

@router.post("/{task_id}/uncomplete")
def uncomplete_task(
    task_id     : UUID,
    db          : Session = Depends(get_db),
    current_user          = Depends(get_current_user),
):
    task = db.query(SmartDailyTask).filter(
        SmartDailyTask.id      == task_id,
        SmartDailyTask.user_id == current_user.id,
    ).first()
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")

    task.completed    = False
    task.completed_at = None
    db.commit()
    return {"success": True}


# ─────────────────────────────────────────────────────────────────────────────
# POST /api/tasks/{task_id}/submit
# User submits their answer/solution — Gemini reviews it and gives feedback
# ─────────────────────────────────────────────────────────────────────────────

@router.post("/{task_id}/submit", response_model=SubmitAnswerResponse)
def submit_task_answer(
    task_id : UUID,
    body    : SubmitAnswerRequest,
    db      : Session = Depends(get_db),
    current_user      = Depends(get_current_user),
):
    """
    User submits their solution/answer to a hard task.
    Gemini reviews it and returns personalised feedback.
    Marks task as completed on submission.
    """
    task = db.query(SmartDailyTask).filter(
        SmartDailyTask.id      == task_id,
        SmartDailyTask.user_id == current_user.id,
    ).first()
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")

    # Build evaluation prompt
    eval_prompt = f"""
You are GrowthOS AI — a concise, encouraging mentor.

TASK: {task.title}
QUESTION: {task.question}
CATEGORY: {task.category}
SKILL: {task.skill_tag}

USER'S ANSWER:
{body.user_answer}

Review their answer in exactly 3 sentences:
1. What they got right (be specific)
2. What they missed or could improve (be constructive)
3. One actionable next step to reinforce this skill

Plain text only. No markdown. Be encouraging but honest.
"""
    profile  = _get_user_profile(current_user.id, db)
    feedback = ask_ai(eval_prompt, profile)

    task.user_answer  = body.user_answer[:3000]
    task.ai_feedback  = feedback
    task.completed    = True
    task.completed_at = datetime.now(timezone.utc)
    db.commit()
    db.refresh(task)

    return SubmitAnswerResponse(
        task_id    = task.id,
        xp_earned  = task.xp_reward,
        ai_feedback= feedback,
        completed  = True,
    )


# ─────────────────────────────────────────────────────────────────────────────
# POST /api/tasks/regenerate
# Manually regenerate today's tasks (user-triggered)
# ─────────────────────────────────────────────────────────────────────────────

@router.post("/regenerate", response_model=List[SmartTaskOut])
def regenerate_today_tasks(
    db          : Session = Depends(get_db),
    current_user          = Depends(get_current_user),
):
    """Delete today's tasks and regenerate fresh ones with Gemini."""
    today = date.today()

    # Delete existing today's tasks
    db.query(SmartDailyTask).filter(
        SmartDailyTask.user_id == current_user.id,
        cast(SmartDailyTask.task_date, Date) == today,
    ).delete(synchronize_session=False)
    db.commit()

    # Generate fresh
    profile    = _get_user_profile(current_user.id, db)
    tasks_data = generate_smart_daily_tasks(profile)

    if not tasks_data:
        raise HTTPException(status_code=500, detail="Task generation failed. Try again.")

    saved = []
    for t in tasks_data:
        task = SmartDailyTask(
            user_id           = current_user.id,
            title             = t.get("title", "Today's Task"),
            question          = t.get("question", ""),
            description       = t.get("description", ""),
            difficulty        = t.get("difficulty", "hard"),
            category          = t.get("category", "Learning"),
            skill_tag         = t.get("skill_tag", ""),
            resource_url      = t.get("resource_url", ""),
            priority          = t.get("priority", "high"),
            estimated_minutes = t.get("estimated_minutes", 45),
            xp_reward         = t.get("xp_reward", 50),
            task_date         = datetime.now(timezone.utc),
        )
        db.add(task)
        saved.append(task)

    db.commit()
    for task in saved:
        db.refresh(task)

    return saved