"""
Backend/nova/resources/types.py

Strongly typed Pydantic models for NOVA Resource Intelligence & Personalized Resource Discovery.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ResourceType(str, Enum):
    VIDEO = "video"
    COURSE = "course"
    DOCUMENTATION = "documentation"
    ARTICLE = "article"
    PRACTICE_SET = "practice_set"
    PROJECT = "project"
    BOOK = "book"
    TUTORIAL = "tutorial"
    TOOL = "tool"
    OTHER = "other"


class ResourceMode(str, Enum):
    LEARN = "learn"
    PRACTICE = "practice"
    UNDERSTAND = "understand"
    REVISE = "revise"
    BUILD = "build"
    PREPARE = "prepare"
    RESEARCH = "research"


class ResourceInteractionType(str, Enum):
    OPENED = "opened"
    COMPLETED = "completed"
    SKIPPED = "skipped"
    HELPFUL = "helpful"
    UNHELPFUL = "unhelpful"


class ResourceItem(BaseModel):
    """Canonical representation of an educational/actionable learning resource."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    title: str
    description: str = ""
    url: str
    canonical_url: Optional[str] = None
    resource_type: ResourceType = ResourceType.OTHER
    provider_platform: str = "web"  # e.g. "YouTube", "Docs", "Coursera", "LeetCode", "GrowthOS"
    author: Optional[str] = None
    source_domain: Optional[str] = None
    subject: Optional[str] = None
    topic: Optional[str] = None
    difficulty: str = "intermediate"  # "beginner" | "intermediate" | "advanced"
    estimated_duration_mins: Optional[int] = None
    published_year: Optional[int] = None
    is_user_provided: bool = False
    metadata: Dict[str, Any] = Field(default_factory=dict)
    discovered_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class ScoredResource(BaseModel):
    """Evaluated resource with granular and composite scoring signals."""
    resource: ResourceItem
    relevance_score: float = 0.0
    authority_score: float = 0.0
    quality_score: float = 0.0
    difficulty_match_score: float = 0.0
    freshness_score: float = 0.0
    time_fit_score: float = 0.0
    goal_alignment_score: float = 0.0
    history_penalty: float = 0.0
    overall_score: float = 0.0
    recommendation_reason: str = ""


class ResourceBundle(BaseModel):
    """Structured, curated bundle of top recommendations (curated decision support)."""
    primary: Optional[ScoredResource] = None       # "Start Here"
    alternative: Optional[ScoredResource] = None   # "If you prefer video/course..."
    practice: Optional[ScoredResource] = None      # "Hands-on Practice"
    reference: Optional[ScoredResource] = None     # "Reference / Documentation"


class ResourceRecommendationPayload(BaseModel):
    """Complete payload generated by Resource Engine and attached to NovaState."""
    query_text: str
    mode: ResourceMode = ResourceMode.LEARN
    recommended_bundle: ResourceBundle = Field(default_factory=ResourceBundle)
    all_ranked_resources: List[ScoredResource] = Field(default_factory=list)
    reasoning_explanation: str = ""
    execution_time_ms: float = 0.0


class ResourceInteractionRecord(BaseModel):
    """Tracked user interaction event on a resource."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    user_id: str
    resource_id: str
    interaction_type: ResourceInteractionType = ResourceInteractionType.OPENED
    time_spent_mins: Optional[int] = None
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
