# models/smart_task.py
# New SmartDailyTask model — extends your existing DailyTask pattern
# Add this alongside your existing models/dashboard.py

import uuid
from datetime import datetime, timezone
from sqlalchemy import Column, String, Integer, Boolean, DateTime, Text
from sqlalchemy.dialects.postgresql import UUID

# Replace with your actual Base import path
from Backend.db.session import Base   # e.g. from database import Base


class SmartDailyTask(Base):
    """
    Career-aware daily tasks with an actual question/problem to solve.
    2 hard tasks + 1 easy task per user per day.
    Generated by Gemini AI at midnight via APScheduler.
    """
    __tablename__ = "smart_daily_tasks"

    id                = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id           = Column(UUID(as_uuid=True), nullable=False, index=True)

    # Task content
    title             = Column(String(200),  nullable=False)
    question          = Column(Text,         nullable=False)   # ← The actual problem to solve
    description       = Column(String(500),  nullable=True)
    difficulty        = Column(String(10),   nullable=False, default="hard")   # "hard" | "easy"
    category          = Column(String(80),   nullable=False, default="Learning")
    skill_tag         = Column(String(80),   nullable=True)
    resource_url      = Column(String(500),  nullable=True)

    # Scheduling
    priority          = Column(String(10),   nullable=False, default="high")   # "high" | "medium"
    estimated_minutes = Column(Integer,      nullable=False, default=45)
    xp_reward         = Column(Integer,      nullable=False, default=50)
    task_date         = Column(DateTime(timezone=True), nullable=False, index=True)

    # Completion tracking
    completed         = Column(Boolean,      nullable=False, default=False)
    completed_at      = Column(DateTime(timezone=True), nullable=True)
    user_answer       = Column(Text,         nullable=True)   # user's submitted solution/answer
    ai_feedback       = Column(Text,         nullable=True)   # AI feedback on their answer

    created_at        = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))