"""
Backend/nova/planner/types.py

Strongly typed Pydantic models for NOVA Planning & Goal Decomposition Engine (Step 9).
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class GoalCategory(str, Enum):
    CAREER = "career"
    EDUCATION = "education"
    BUSINESS = "business"
    CREATOR = "creator"
    FREELANCE = "freelance"
    PERSONAL = "personal"
    TECHNOLOGY = "technology"


class HorizonType(str, Enum):
    SHORT_TERM = "short_term"  # Days
    WEEKLY = "weekly"          # 1-2 Weeks
    MEDIUM_TERM = "medium_term"# Weeks / Months
    LONG_TERM = "long_term"    # Months / Year+


class TaskItemType(str, Enum):
    LEARN = "learn"
    PRACTICE = "practice"
    BUILD = "build"
    REVISE = "revise"
    RESEARCH = "research"
    ASSESS = "assess"
    REFLECT = "reflect"


class PriorityLevel(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class PlanStatus(str, Enum):
    DRAFT = "draft"
    ACTIVE = "active"
    COMPLETED = "completed"
    REVISED = "revised"
    ARCHIVED = "archived"


class TaskDependency(BaseModel):
    """Explicit dependency link between tasks."""
    task_id: str
    depends_on_task_id: str
    dependency_type: str = "prerequisite"  # "prerequisite" | "blocking" | "optional"


class GapAnalysisItem(BaseModel):
    """Gap identified between user's current state and target goal."""
    skill_or_topic: str
    current_level: str = "none"       # "none" | "beginner" | "intermediate" | "advanced"
    target_level: str = "intermediate"
    importance: PriorityLevel = PriorityLevel.HIGH
    effort_mins: int = 60
    prerequisites: List[str] = Field(default_factory=list)


class TaskItem(BaseModel):
    """Executable task item within an objective."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    title: str
    description: str = ""
    task_type: TaskItemType = TaskItemType.LEARN
    priority: PriorityLevel = PriorityLevel.MEDIUM
    estimated_minutes: int = 30
    difficulty: str = "intermediate"
    status: str = "pending"
    prerequisites: List[str] = Field(default_factory=list)
    completion_criteria: str = "Task completed successfully."
    resource_ids: List[str] = Field(default_factory=list)
    due_at: Optional[str] = None


class ObjectiveItem(BaseModel):
    """Sub-goal objective containing granular actionable tasks."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    title: str
    description: str = ""
    tasks: List[TaskItem] = Field(default_factory=list)


class MilestoneItem(BaseModel):
    """Major phase milestone containing objectives."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    title: str
    description: str = ""
    objectives: List[ObjectiveItem] = Field(default_factory=list)


class PlanPhaseItem(BaseModel):
    """Top-level strategic roadmap phase."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    phase_number: int = 1
    title: str
    theme: str = ""
    milestones: List[MilestoneItem] = Field(default_factory=list)


class PlanningPayload(BaseModel):
    """Complete planning payload generated by NovaPlanner and attached to NovaState."""
    goal_title: str
    goal_category: GoalCategory = GoalCategory.CAREER
    horizon: HorizonType = HorizonType.MEDIUM_TERM
    user_current_state: str = ""
    gap_analysis: List[GapAnalysisItem] = Field(default_factory=list)
    phases: List[PlanPhaseItem] = Field(default_factory=list)
    total_estimated_mins: int = 0
    daily_time_budget_mins: int = 60
    time_feasibility_status: str = "feasible"  # "feasible" | "tight" | "overloaded"
    assumptions: List[str] = Field(default_factory=list)
    confidence: float = 0.90
    plan_version: int = 1
    execution_time_ms: float = 0.0
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
