"""
Backend/nova/progress/types.py

Strongly typed Pydantic models for NOVA Execution & Progress Intelligence Engine (Step 10).
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ExecutionEventType(str, Enum):
    TASK_STARTED = "task_started"
    TASK_COMPLETED = "task_completed"
    TASK_PARTIALLY_COMPLETED = "task_partially_completed"
    TASK_FAILED = "task_failed"
    TASK_SKIPPED = "task_skipped"
    TASK_PAUSED = "task_paused"
    TASK_RESUMED = "task_resumed"
    TASK_ABANDONED = "task_abandoned"


class TaskExecutionState(str, Enum):
    NOT_STARTED = "not_started"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    PARTIAL = "partial"
    SKIPPED = "skipped"
    FAILED = "failed"
    BLOCKED = "blocked"
    CANCELLED = "cancelled"


class ProgressSignalType(str, Enum):
    ON_TRACK = "on_track"
    AHEAD = "ahead"
    BEHIND = "behind"
    STRUGGLING = "struggling"
    INCONSISTENT = "inconsistent"
    OVERLOADED = "overloaded"
    IMPROVING = "improving"
    STAGNATING = "stagnating"
    BLOCKED = "blocked"
    AT_RISK = "at_risk"
    CAPACITY_HIGHER = "capacity_higher"
    DIFFICULTY_MISMATCH = "difficulty_mismatch"


class AdaptationSignalType(str, Enum):
    NO_ACTION = "no_action"
    REDUCE_WORKLOAD = "reduce_workload"
    INCREASE_WORKLOAD = "increase_workload"
    INSERT_PREREQUISITE = "insert_prerequisite"
    ADJUST_TIMELINE = "adjust_timeline"
    REORDER_TASKS = "reorder_tasks"
    ASK_CLARIFICATION = "ask_clarification"


class ExecutionEventRecord(BaseModel):
    """Raw execution event emitted during user work."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    user_id: str
    task_id: str
    plan_id: Optional[str] = None
    goal_id: Optional[str] = None
    event_type: ExecutionEventType = ExecutionEventType.TASK_COMPLETED
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    duration_seconds: int = 0
    completion_percentage: float = 100.0
    difficulty_rating: Optional[str] = None  # "too_easy" | "just_right" | "too_hard"
    user_feedback: Optional[str] = None
    notes: Optional[str] = None
    idempotency_key: Optional[str] = None


class ProgressSnapshot(BaseModel):
    """Multidimensional hierarchical progress snapshot."""
    task_progress_pct: float = 0.0
    objective_progress_pct: float = 0.0
    milestone_progress_pct: float = 0.0
    phase_progress_pct: float = 0.0
    plan_progress_pct: float = 0.0
    goal_progress_pct: float = 0.0
    actual_vs_estimated_ratio: float = 1.0


class ProgressSignal(BaseModel):
    """Structured progress intelligence signal detected from execution patterns."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    signal_type: ProgressSignalType = ProgressSignalType.ON_TRACK
    title: str
    description: str
    confidence: float = 0.90
    evidence: List[str] = Field(default_factory=list)
    affected_task_id: Optional[str] = None


class AdaptationSignal(BaseModel):
    """Structured signal emitted to Step 9 Planner for plan adaptation."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    adaptation_type: AdaptationSignalType = AdaptationSignalType.NO_ACTION
    reason: str
    recommended_action: str = ""
    confidence: float = 0.85
    target_task_id: Optional[str] = None


class ProgressPayload(BaseModel):
    """Complete progress payload generated by ProgressManager and attached to NovaState."""
    user_id: str
    plan_id: Optional[str] = None
    snapshot: ProgressSnapshot = Field(default_factory=ProgressSnapshot)
    active_signals: List[ProgressSignal] = Field(default_factory=list)
    adaptation_signals: List[AdaptationSignal] = Field(default_factory=list)
    recent_events: List[ExecutionEventRecord] = Field(default_factory=list)
    execution_time_ms: float = 0.0
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
